[2024-09-26 20:04:56,145] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 20:04:56] "GET /cliente?id=1 HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 20:05:36,846] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 20:05:36] "GET /cliente?id=1 HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 20:06:04,881] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 20:06:04] "GET /cliente?id=1 HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 20:08:00,742] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 20:08:00] "GET /cliente?id=1 HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 20:09:48,731] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 20:09:48] "GET /cliente?id=1 HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 20:11:12,073] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 20:11:12] "GET /cliente?id=1 HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 20:12:25,561] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 20:12:25] "GET /cliente?id=1 HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 21:51:28,016] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 21:51:28] "GET /cliente?id=3 HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-27 01:32:58,671] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9000
 * Running on http://172.20.0.2:9000 - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:32:58,674] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:32:58,676] INFO _log() L97    * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:42:01,880] INFO _log() L97    * Detected change in '/app/schemas/cliente.py', reloading - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:42:02,017] INFO _log() L97    * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:42:54,244] INFO _log() L97    * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:43:49,203] INFO _log() L97    * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:44:48,220] INFO _log() L97    * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:44:55,403] INFO _log() L97    * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:44:59,387] INFO _log() L97    * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:45:02,349] INFO _log() L97    * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-26 22:52:32,957] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9000
 * Running on http://192.168.1.69:9000 - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:52:32,957] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:52:36,325] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:52:36] "[33mGET /cliente?id=1 HTTP/1.1[0m" 404 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:52:43,540] ERROR log_exception() L838  Exception on /endereco [GET] - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\app.py", line 86, in get_endereco
    endereco = session.query(endereco).filter(endereco.id == endereco_id).first()
                             ^^^^^^^^
UnboundLocalError: cannot access local variable 'endereco' where it is not associated with a value
[2024-09-26 22:52:43,555] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:52:43] "[35m[1mGET /endereco?id=1 HTTP/1.1[0m" 500 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:52:56,499] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:52:56] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:52:56,622] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:52:56] "GET /openapi/static/css/swagger-ui.css HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:52:56,668] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:52:56] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:52:56,737] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:52:56] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:52:56,859] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:52:56] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:53:07,849] ERROR log_exception() L838  Exception on /endereco [POST] - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Python-Secundaria\app.py", line 51, in add_endereco
    endereco = endereco(
               ^^^^^^^^
UnboundLocalError: cannot access local variable 'endereco' where it is not associated with a value
[2024-09-26 22:53:07,852] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:53:07] "[35m[1mPOST /endereco HTTP/1.1[0m" 500 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:54:04,668] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:54:04] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Python-Secundaria\env\Lib\site-packages\werkzeug\_internal.py L97  
